config/routes.rb
Donations::Application.routes.draw do
  root to: 'organizations#index'
  resources :organizations
  resources :charges
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :organization
  belongs_to :customer
  validates :amount, presence: true

  def self.stripe_process_charge(params)
    @amount = params[:charge][:amount]

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
  end

  def self.save_charge(customer_id, params)
    charge = Charge.new(params)
    charge.customer_id = customer_id
    charge.save
    charge
  end
end

app/models/customer.rb
class Customer< ActiveRecord::Base
  has_many :charges
  has_many :organizations, through: :charges


  def self.save_customer(params)
    if Customer.find_by_email(params[:stripeEmail]).nil?
      new_customer = Customer.new()
      new_customer[:name]=params[:stripeBillingName]
      new_customer[:email]=params[:stripeEmail]
      new_customer[:address]=params[:stripeBillingAddressLine1]
      new_customer[:zip]=params[:stripeBillingAddressZip]
      new_customer[:city]=params[:stripeBillingAddressCity]
      new_customer[:state]=params[:stripeBillingAddressState]
      new_customer[:country]=params[:stripeBillingAddressCountry]
      new_customer[:county_code]=params[:stripeBillingAddressCountryCode]
      new_customer.save
    else
      new_customer = Customer.find_by_email(params[:stripeEmail])
    end
    new_customer

  end

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :charges
  has_many :organizations, through: :charges
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :charges
  has_many :customers, through: :charges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
require 'pry'
class ChargesController < ApplicationController
  def index
    @charges = Charge.all
  end

  def new
    @charge = Charge.new
  end

  def create
    begin
      if Charge.stripe_process_charge(params)
        customer = Customer.save_customer(cust_params)
        charge = Charge.save_charge(customer.id,charge_params)
      end
      flash[:notice] = "success"
      redirect_to root_path
    rescue Stripe::CardError => e
      flash[:notice] = e.message
      redirect_to root_path
    end
  end

private
  def cust_params
    params.permit(:stripeBillingName,
                  :stripeEmail,
                  :stripeBillingAddressLine1,
                  :stripeBillingAddressZip,
                  :stripeBillingAddressCity,
                  :stripeBillingAddressState,
                  :stripeBillingAddressCountry,
                  :stripeBillingAddressCountryCode )
  end

  def charge_params
    params.require(:charge).permit(:amount, :organization_id)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.create(organization_params)
    flash[:notice] = "Organization created"
    redirect_to organizations_path
  end

  def show
    @organization = Organization.find(params[:id])
  end

private
  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/index.html.erb
<h2>Charges</h2>

<ul>
  <% @charges.each do |charge| %>

    <li><%= charge.customer.name %> made a donation of <%= number_to_currency("#{(charge.amount)/100}") %> to <%= charge.organization.name %> </li>

  <% end %>
</ul>

app/views/charges/new.html.erb
<%= form_for @charge do |form| %>

  <%= form.label :amount %>
  <%= form.text_field :amount %>
  <%= form.collection_select :organization_id, Organization.all.order(:name), :id, :name %>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Donations"
    data-address=""
    data-amount="">
  </script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donations</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= flash[:notice] %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for @organization do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>

<% end %>

app/views/organizations/index.html.erb
<h2>Organizations</h2>

<ul>
  <% @organizations.each do |org| %>

    <li><%= link_to org.name, organization_path(org) %></li>

  <% end %>
</ul>

app/views/organizations/new.html.erb
<h2>Add an organization</h2>


<%= render 'form' %>

app/views/organizations/show.html.erb
<h2><%= @organization.name %></h2>


<p>Link to make a donation and home page</p>